# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rexo < Formula
  desc "REXO — Runtime for Execution & eXchange Orchestration."
  homepage "https://github.com/lanroo/rexo"
  version "0.0.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.9/rexo_darwin_amd64.tar.gz"
      sha256 "5b96f8b973a4130496ba09c8160a1ebd3600283debe7db2ecbdb1bd441aaf277"

      define_method(:install) do
        bin.install "rexo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.9/rexo_darwin_arm64.tar.gz"
      sha256 "b3cb7891495db5677f2e7e0f5e54ce9fd5ae0c4844841fdbd894080610e4bb15"

      define_method(:install) do
        bin.install "rexo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.9/rexo_linux_amd64.tar.gz"
      sha256 "315305bfa77773dff6a1106462cb731210b2d64ad3238c03c9ee3040963b24e8"
      define_method(:install) do
        bin.install "rexo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.9/rexo_linux_arm64.tar.gz"
      sha256 "74286f0bb79b35dd22acf3e2eeb4faf48a31d5bf840abe71f93822c19f10a7aa"
      define_method(:install) do
        bin.install "rexo"
      end
    end
  end

  test do
    system "#{bin}/rexo", "version"
  end
end
