# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rexo < Formula
  desc "REXO — Runtime for Execution & eXchange Orchestration."
  homepage "https://github.com/lanroo/rexo"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.6/rexo_darwin_amd64.tar.gz"
      sha256 "d62e1dc8ed9f16ca14c4d707b9f4635b23ea57d36dd7bf65e6e71532e02d6c38"

      define_method(:install) do
        bin.install "rexo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.6/rexo_darwin_arm64.tar.gz"
      sha256 "493d0d880495e959ceec6d93d4425ce466d78c9c70e8b89e7a94327c56f7ee39"

      define_method(:install) do
        bin.install "rexo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.6/rexo_linux_amd64.tar.gz"
      sha256 "02fa437fcb66f8ebf84f89d85e1416b836e775746dd0406ac8b2722a8c425878"
      define_method(:install) do
        bin.install "rexo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanroo/rexo/releases/download/v0.0.6/rexo_linux_arm64.tar.gz"
      sha256 "2acc1cb5f09db21f0f375697155c063e4b1a1692dbb9e8d597c4bed6a33dc27a"
      define_method(:install) do
        bin.install "rexo"
      end
    end
  end

  test do
    system "#{bin}/rexo", "version"
  end
end
